app:
  security:
    role:
      admin: "ADMIN"
      fan: FAN
      vendor: "VENDOR"

spring:
  profiles:
    active: ${DEPLOY_ENV:default}
  application:
    name: merch-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    open-in-view: false
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:8083/auth/realms/baeldung
  #         jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs