
logging:
  level:
    root: info
    org.daemio: info
    org.hibernate: info
    
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      roles: 'ADMIN'
      show-details: when-authorized
    info:
      enabled: true
  tracing:
    enabled: true

spring:
  profiles:
    active: ${DEPLOY_ENV:default}
  application:
    name: merch-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    open-in-view: false
    show-sql: true
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: ${ISSUER_URI:http://localhost:8083/auth}
  #         jwk-set-uri: ${JWK_SET_URI:http://localhost:8083/auth/.well-known/jwks.json}
  liquibase:
    change-log: classpath:db/changelog.yaml
    drop-first: false
    enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false