spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:sqlite-integ.db
    username:
    password:
  liquibase:
    enabled: true