logging:
  level: 
    root: info
    com:
      daemio: trace

app:
  security:
    jwt:
      secret-key: ${SECRET_KEY}

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:sqlite-integ.db
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    drop-first: false