logging:
  level: 
    root: info
    com:
      daemio: trace

app:
  security:
    jwt:
      secret-key: ${SECRET_KEY:mIAWni0nnXlQmCBOVZxwXi6+c4JKhzqJgXct8oBWX5B1mwZlVfqj/k6Z98XHrhtP}

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect